/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type B2ShareExtractedSchema = {
  created: string;
  links: Links;
  files: Files[];
  metadata: Metadata;
};

type Files = {
  bucket?: string;
  checksum?: string;
  ePIC_PID?: string;
  key?: string;
  size?: number;
  version_id?: string;
};

type Links = {
  files?: string;
  self?: string;
  versions?: string;
};

export type Metadata = {
  $schema?: string;
  DOI?: string;
  creators?: Creators;
  titles: Titles;
  publisher?: Publisher;
  publication_date?: PublicationDate;
  resource_types?: ResourceType;
  instruments?: Instruments;
  disciplines?: Disciplines;
  keywords?: Keywords;
  contributors?: Contributors;
  languages?: Languages;
  alternate_identifiers?: AlternateIdentifier;
  related_identifiers?: RelatedIdentifiers;
  descriptions?: Descriptions;
  version?: Version;
  contact_email?: ContactEmail;
  open_access: OpenAccess;
  embargo_date?: EmbargoDate;
  license?: License;
  language?: string;
  dates?: Dates;
  sizes?: Sizes;
  formats?: Formats;
  spatial_coverages?: SpatialCoverages;
  temporal_coverages?: TemporalCoverages;
  funding_references?: FundingReferences;
  community: Community;
  community_specific: {
    [k: string]: unknown;
  };
  publication_state: PublicationState;
  _pid?: PersistentIdentifiers;
  _deposit?: {
    [k: string]: unknown;
  };
  _oai?: {
    [k: string]: unknown;
  };
  _files?: unknown[];
} & {
  community_specific?: {};
  [k: string]: unknown;
};
/**
 * The first names given to this entity.
 */
export type GivenName = string;
/**
 * The family names given to this entity.
 */
export type FamilyName = string;
/**
 * The unique identifier of the affiliation.
 */
export type Identifier = string;
/**
 * The scheme used for the identifier.
 */
export type Scheme = string;
/**
 * The organisations or entities this entity is affiliated with.
 */
export type Affiliations = {
  /**
   * The name of the affiliation.
   */
  affiliation_name: string;
  affiliation_identifier?: Identifier;
  scheme?: Scheme;
  [k: string]: unknown;
}[];
/**
 * The type of name described.
 */
export type NameType = 'Personal' | 'Organizational';
/**
 * The scheme used for the identifier.
 */
export type Scheme1 = string;
/**
 * The URI pointing to the scheme.
 */
export type SchemeURI = string;
/**
 * The identifiers that point to any information about this creator.
 */
export type NameIdentifiers = {
  /**
   * The unique identifier of the entity, according to various identifier schemes.
   */
  name_identifier: string;
  scheme: Scheme1;
  scheme_uri?: SchemeURI;
  [k: string]: unknown;
}[];
/**
 * The full name of the creators. The personal name format should be: family, given (e.g.: Smith, John).
 */
export type Creators = {
  creator_name: string;
  given_name?: GivenName;
  family_name?: FamilyName;
  affiliations?: Affiliations;
  name_type?: NameType;
  name_identifiers?: NameIdentifiers;
  [k: string]: unknown;
}[];
/**
 * The titles(s) of the uploaded resource, or a name by which the resource is known.
 *
 * @minItems 1
 */
export type Titles = [
  {
    title: string;
    type?: Type;
  },
  ...{
    title: string;
    type?: Type;
  }[],
];
/**
 * The type of the title.
 */
export type Type = 'Alternative Title' | 'Subtitle' | 'TranslatedTitle' | 'Other';
/**
 * The entity responsible for making the resource available, either a person, an organization, or a service.
 */
export type Publisher = string;
/**
 * The date when the data was or will be made publicly available (e.g. 2018-07-13)
 */
export type PublicationDate = string;
/**
 * The type(s) of the resource.
 *
 * @minItems 1
 */
export type ResourceType = [
  {
    resource_type_general: Type1;
    resource_type_description?: Description;
  },
  ...{
    resource_type_general: Type1;
    resource_type_description?: Description;
  }[],
];
export type Type1 =
  | 'Audiovisual'
  | 'Book'
  | 'BookChapter'
  | 'Collection'
  | 'ComputationalNotebook'
  | 'ConferencePaper'
  | 'ConferenceProceeding'
  | 'DataPaper'
  | 'Dataset'
  | 'Dissertation'
  | 'Event'
  | 'Image'
  | 'InteractiveResource'
  | 'Journal'
  | 'JournalArticle'
  | 'Model'
  | 'OutputManagementPlan'
  | 'PeerReview'
  | 'PhysicalObject'
  | 'Preprint'
  | 'Report'
  | 'Service'
  | 'Software'
  | 'Sound'
  | 'Standard'
  | 'Text'
  | 'Workflow'
  | 'Other';
/**
 * An optional description of the resource type.
 */
export type Description = string;
/**
 * The unique identifier of the instrument.
 */
export type Identifier1 = string;
/**
 * The type of the identifier.
 */
export type Type2 =
  | 'ARK'
  | 'arXiv'
  | 'bibcode'
  | 'DOI'
  | 'EAN13'
  | 'EISSN'
  | 'Handle'
  | 'ISBN'
  | 'ISSN'
  | 'ISTC'
  | 'LISSN'
  | 'LSID'
  | 'ORCID'
  | 'PMID'
  | 'PURL'
  | 'UPC'
  | 'URL'
  | 'URN'
  | 'w3id';
/**
 * The scientific instruments the data was generated or captured on.
 */
export type Instruments = {
  instrument_name: string;
  instrument_identifier?: Identifier1;
  instrument_identifier_type?: Type2;
  [k: string]: unknown;
}[];
/**
 * The unique identifier of the discipline, according to various identifier schemes.
 */
export type Identifier2 = string;
/**
 * The corresponding classification code of the discipline, according to various identifier schemes.
 */
export type Code = string;
/**
 * The scheme used for the identifier.
 */
export type Scheme2 = string;
/**
 * The URI pointing to the scheme.
 */
export type SchemeURI1 = string;
/**
 * The scientific disciplines linked with the resource.
 */
export type Disciplines = {
  discipline_name: string;
  discipline_identifier: Identifier2;
  classification_code?: Code;
  scheme?: Scheme2;
  scheme_uri?: SchemeURI1;
  [k: string]: unknown;
}[];
/**
 * The corresponding classification code of the keyword, according to various identifier schemes.
 */
export type Code1 = string;
/**
 * The scheme used for the identifier.
 */
export type Scheme3 = string;
/**
 * The URI pointing to the scheme.
 */
export type SchemeURI2 = string;
/**
 * The keywords or key phrases describing the resource.
 */
export type Keywords = {
  keyword: string;
  classification_code?: Code1;
  scheme?: Scheme3;
  scheme_uri?: SchemeURI2;
  [k: string]: unknown;
}[];
/**
 * The first names given to this entity.
 */
export type GivenName1 = string;
/**
 * The family names given to this entity.
 */
export type FamilyName1 = string;
/**
 * The unique identifier of the affiliation.
 */
export type Identifier3 = string;
/**
 * The scheme used for the identifier.
 */
export type Scheme4 = string;
/**
 * The organisations or entities this entity is affiliated with.
 */
export type Affiliations1 = {
  /**
   * The name of the affiliation.
   */
  affiliation_name: string;
  affiliation_identifier?: Identifier3;
  scheme?: Scheme4;
  [k: string]: unknown;
}[];
/**
 * The type of name described.
 */
export type NameType1 = 'Personal' | 'Organizational';
/**
 * The scheme used for the identifier.
 */
export type Scheme5 = string;
/**
 * The URI pointing to the scheme.
 */
export type SchemeURI3 = string;
/**
 * The identifiers that point to any information about this creator.
 */
export type NameIdentifiers1 = {
  /**
   * The unique identifier of the entity, according to various identifier schemes.
   */
  name_identifier: string;
  scheme: Scheme5;
  scheme_uri?: SchemeURI3;
  [k: string]: unknown;
}[];
/**
 * The type of the contributor.
 */
export type ContributorType =
  | 'ContactPerson'
  | 'DataCollector'
  | 'DataCurator'
  | 'DataManager'
  | 'Distributor'
  | 'Editor'
  | 'HostingInstitution'
  | 'Producer'
  | 'ProjectLeader'
  | 'ProjectManager'
  | 'ProjectMember'
  | 'RegistrationAgency'
  | 'RegistrationAuthority'
  | 'RelatedPerson'
  | 'Researcher'
  | 'ResearchGroup'
  | 'RightsHolder'
  | 'Sponsor'
  | 'Supervisor'
  | 'WorkPackageLeader'
  | 'Other';
/**
 * The list of all other contributors. Please mention all persons that were relevant in the creation of the resource.
 */
export type Contributors = {
  contributor_name: string;
  given_name?: GivenName1;
  family_name?: FamilyName1;
  affiliations?: Affiliations1;
  name_type?: NameType1;
  name_identifiers?: NameIdentifiers1;
  contributor_type: ContributorType;
}[];
/**
 * The identifier for the language, according to various identifier schemes.
 */
export type Identifier4 = string;
/**
 * The scheme used for the identifier.
 */
export type Scheme6 = string;
/**
 * The URI pointing to the scheme.
 */
export type SchemeURI4 = string;
/**
 * The language(s) of the contents of the resource. Allowed values should be taken from ISO 639-1 and 639-3 language codes or IETF BCP 47. Examples: en, de or deu, eng or de-AT, en-US.
 */
export type Languages = {
  language_name: string;
  language_identifier: Identifier4;
  scheme?: Scheme6;
  scheme_uri?: SchemeURI4;
  [k: string]: unknown;
}[];
/**
 * The type of the identifier.
 */
export type Type3 =
  | 'ARK'
  | 'arXiv'
  | 'bibcode'
  | 'DOI'
  | 'EAN13'
  | 'EISSN'
  | 'Handle'
  | 'ISBN'
  | 'ISSN'
  | 'ISTC'
  | 'LISSN'
  | 'LSID'
  | 'ORCID'
  | 'PMID'
  | 'PURL'
  | 'UPC'
  | 'URL'
  | 'URN'
  | 'w3id';
/**
 * The alternative identifiers for this resource such as a URN, URI or an ISBN number.
 */
export type AlternateIdentifier = {
  alternate_identifier: string;
  alternate_identifier_type: Type3;
}[];
/**
 * The type of the resource.
 */
export type ResourceType1 =
  | 'Audiovisual'
  | 'Book'
  | 'BookChapter'
  | 'Collection'
  | 'ComputationalNotebook'
  | 'ConferencePaper'
  | 'ConferenceProceeding'
  | 'DataPaper'
  | 'Dataset'
  | 'Dissertation'
  | 'Event'
  | 'Image'
  | 'InteractiveResource'
  | 'Journal'
  | 'JournalArticle'
  | 'Model'
  | 'OutputManagementPlan'
  | 'PeerReview'
  | 'PhysicalObject'
  | 'Preprint'
  | 'Report'
  | 'Service'
  | 'Software'
  | 'Sound'
  | 'Standard'
  | 'Text'
  | 'Workflow'
  | 'Other';
/**
 * The type of the identifier.
 */
export type Type4 =
  | 'ARK'
  | 'arXiv'
  | 'bibcode'
  | 'DOI'
  | 'EAN13'
  | 'EISSN'
  | 'Handle'
  | 'ISBN'
  | 'ISSN'
  | 'ISTC'
  | 'LISSN'
  | 'LSID'
  | 'ORCID'
  | 'PMID'
  | 'PURL'
  | 'UPC'
  | 'URL'
  | 'URN'
  | 'w3id';
/**
 * The relation type of the described reference.
 */
export type Relation =
  | 'IsCitedBy'
  | 'Cites'
  | 'IsSupplementTo'
  | 'IsPublishedIn'
  | 'IsSupplementedBy'
  | 'IsContinuedBy'
  | 'Continues'
  | 'HasMetadata'
  | 'IsMetadataFor'
  | 'IsNewVersionOf'
  | 'IsPreviousVersionOf'
  | 'IsPartOf'
  | 'HasPart'
  | 'IsReferencedBy'
  | 'References'
  | 'IsDocumentedBy'
  | 'Documents'
  | 'isCompiledBy'
  | 'Compiles'
  | 'IsVariantFormOf'
  | 'IsOriginalFormOf'
  | 'IsIdenticalTo'
  | 'IsReviewedBy'
  | 'Reviews'
  | 'IsDerivedFrom'
  | 'IsSourceOf'
  | 'Describes'
  | 'IsDescribedBy'
  | 'HasVersion'
  | 'IsVersionOf'
  | 'Requires'
  | 'IsRequiredBy'
  | 'Obsoletes'
  | 'IsObsoletedBy';
/**
 * The scheme used for the identifier.
 */
export type Scheme7 = string;
/**
 * The URI pointing to the scheme.
 */
export type SchemeURI5 = string;
/**
 * The identifiers of other resources related to the resource such as a URN, URI or an ISBN number.
 */
export type RelatedIdentifiers = {
  related_identifier: string;
  resource_type_general?: ResourceType1;
  related_identifier_type: Type4;
  relation_type: Relation;
  scheme?: Scheme7;
  scheme_uri?: SchemeURI5;
  [k: string]: unknown;
}[];
/**
 * The type of the description.
 */
export type Type5 = 'Abstract' | 'Methods' | 'SeriesInformation' | 'TableOfContents' | 'TechnicalInfo' | 'Other';
/**
 * The more elaborate description of the resource. Focus on a content description that makes it easy for others to find, and to interpret its relevance.
 */
export type Descriptions = {
  description: string;
  description_type: Type5;
}[];
/**
 * The version of the resource.
 */
export type Version = string;
/**
 * The contact email information for this resource.
 */
export type ContactEmail = string;
/**
 * Indicate whether the record's files are publicly accessible or not. In case of restricted access the uploaded files will only be accessible by the record's owner and the community administrators. Please note that the record's metadata is always publicly accessible.
 */
export type OpenAccess = boolean;
/**
 * The date marking the end of the embargo period. The record will be marked as open access on the specified date at midnight. Please note that the record metadata is always publicly accessible, and only the data files can have private access.
 */
export type EmbargoDate = string;
/**
 * The URI pointing to the description of the license.
 */
export type LicenseURI = string;
/**
 * The unique identifier of the license, according to various identifier schemes.
 */
export type Identifier5 = string;
/**
 * The scheme used for the identifier.
 */
export type Scheme8 = string;
/**
 * The URI pointing to the scheme.
 */
export type SchemeURI6 = string;
export type Date = string;
/**
 * The type of the date.
 */
export type DateType =
  | 'Accepted'
  | 'Available'
  | 'Collected'
  | 'Copyrighted'
  | 'Created'
  | 'Issued'
  | 'Other'
  | 'Submitted'
  | 'Updated'
  | 'Valid'
  | 'Withdrawn';
/**
 * The additional information about the date.
 */
export type DateInformation = string;
/**
 * The dates related to the resource
 */
export type Dates = {
  date: Date;
  date_type: DateType;
  date_information?: DateInformation;
}[];
/**
 * The unstructured size information about the resource
 */
export type Sizes = string[];
/**
 * The technical formats of the resource.
 */
export type Formats = string[];
/**
 * The name of a place or location.
 */
export type Place = string;
/**
 * The longitude of the point.
 */
export type Longitude = number;
/**
 * The latitude of the point.
 */
export type Latitude = number;
/**
 * The westbound longitude of the enclosing box.
 */
export type WestboundLongitude = number;
/**
 * The eastbound longitude of the enclosing box.
 */
export type EastboundLongitude = number;
/**
 * The northbound latitude of the enclosing box.
 */
export type NorthboundLatitude = number;
/**
 * The southbound latitude of the enclosing box.
 */
export type SouthboundLatitude = number;
/**
 * The longitude of the point.
 */
export type Longitude1 = number;
/**
 * The latitude of the point.
 */
export type Latitude1 = number;
/**
 * A drawn polygon area, defined by a set of points and lines connecting the points in a closed chain.
 */
export type Polygon = {
  point_longitude: Longitude1;
  point_latitude: Latitude1;
  [k: string]: unknown;
}[];
/**
 * The longitude of the point.
 */
export type Longitude2 = number;
/**
 * The latitude of the point.
 */
export type Latitude2 = number;
/**
 * One or more drawn polygon areas, defined by a set of points and lines connecting the points in a closed chain.
 */
export type Polygons = {
  polygon?: Polygon;
  inpoint?: InternalPoint;
  [k: string]: unknown;
}[];
/**
 * The spatial coverages of the contents of the resource.
 */
export type SpatialCoverages = {
  place?: Place;
  point?: Point;
  box?: Boxes;
  polygons?: Polygons;
  [k: string]: unknown;
}[];
/**
 * The start date and time of the range covered by the resource.
 */
export type StartDate = string;
/**
 * The end date and time of the range covered by the resource.
 */
export type EndDate = string;
/**
 * The temporal ranges of the contents of the resource.
 */
export type Ranges = {
  start_date?: StartDate;
  end_date?: EndDate;
  [k: string]: unknown;
}[];
/**
 * The named spans of the contents of the resource.
 */
export type Spans = string[];
/**
 * The full name of the funder.
 */
export type FunderName = string;
/**
 * The type of the identifier of the funder.
 */
export type Type6 = 'ISNI' | 'GRID' | 'ROR' | 'Crossref Funder ID' | 'Other';
/**
 * The URI pointing to the scheme.
 */
export type SchemeURI7 = string;
/**
 * The title of the award.
 */
export type AwardTitle = string;
/**
 * The corresponding number of the award.
 */
export type AwardNumber = string;
/**
 * The URI pointing to the award.
 */
export type AwardURI = string;
/**
 * The information about financial support (funding) for the resource being registered.
 */
export type FundingReferences = {
  funder_name: FunderName;
  /**
   * The unique identifier of the funder.
   */
  funder_identifier?: string;
  funder_identifier_type?: Type6;
  scheme_uri?: SchemeURI7;
  award_title?: AwardTitle;
  award_number?: AwardNumber;
  award_uri?: AwardURI;
  [k: string]: unknown;
}[];
/**
 * The community to which the record has been submitted.
 */
export type Community = string;
/**
 * State of the publication workflow.
 */
export type PublicationState = 'draft' | 'submitted' | 'published';

/**
 * The license under which this data set is available to the users (e.g. GPL, Apache v2 or Commercial). Please use the License Selector for help and additional information.
 */
export interface License {
  license: string;
  license_uri?: LicenseURI;
  license_identifier?: Identifier5;
  scheme?: Scheme8;
  scheme_uri?: SchemeURI6;
}
/**
 * A point contains a single latitude-longitude pair.
 */
export interface Point {
  point_longitude: Longitude;
  point_latitude: Latitude;
  [k: string]: unknown;
}
/**
 * A bounding box defined by two points.
 */
export interface Boxes {
  westbound_longitude: WestboundLongitude;
  eastbound_longitude: EastboundLongitude;
  northbound_latitude: NorthboundLatitude;
  southbound_latitude: SouthboundLatitude;
  [k: string]: unknown;
}
/**
 * A point inside the polygon
 */
export interface InternalPoint {
  point_longitude: Longitude2;
  point_latitude: Latitude2;
  [k: string]: unknown;
}
/**
 * The temporal coverage of the contents of the resource.
 */
export interface TemporalCoverages {
  ranges?: Ranges;
  spans?: Spans;
  [k: string]: unknown;
}
/**
 * Array of persistent identifiers pointing to this record.
 */
export interface PersistentIdentifiers {
  [k: string]: unknown;
}
